TME-2307: add support for existing trail with x-account resources
expel-io/terraform-aws-cloudtrail pull request #46
Opened 2023-08-07 16:19 UTC by sarjumulmi

> Add support for existing cloudtrail with resources deployed in different aws accounts.

Changes:
- `configuration_alias` added for log bucket account. need to pass in the provider alias for log bucket when invoking the module
- conditionally create resources based on `is_existing_cloudtrail_cross_account` var
- local runtime check for assuring other dependent optional variables are provided when `is_existing_cloudtrail_cross_account` is set to true.
- new variable for `expel assume role name` instead of hard coded string. add type defn for `tags`

2023-08-07 17:13 UTC, bachu20 commented on examples/existing-cloudtrail/cross-account/terraform.tfvars
> +existing_cloudtrail_log_bucket_account_id = "Replace with your AWS cloudtrail log bucket account id"
Nit:
```suggestion
existing_cloudtrail_log_bucket_account_id = "Replace with your AWS CloudTrail log bucket account id"
```

2023-08-07 17:14 UTC, bachu20 commented on variables.tf
> +  type        = map(string)
Sweet, thanks for knocking this out too!

2023-08-08 13:53 UTC, bachu20 submitted a review, later dismissed
lgtm. Would definitely defer to @davidmontoyago + @ethanmil for reviews before merging it in.

2023-08-09 13:14 UTC, sarjumulmi commented on README.md
> +| <a name="input_is_existing_cloudtrail_cross_account"></a> [is\_existing\_cloudtrail\_cross\_account](#input\_is\_existing\_cloudtrail\_cross\_account) | For an existing cloudtrail, whether the clou
this applies to cases where you have an existing organization cloudtrail but the cloudtrail log bucket account is NOT in the management account.

2023-08-10 18:02 UTC, ethanmil requested changes
Looking good! Just a few typos and readability suggestions.

2023-08-10 18:02 UTC, ethanmil commented on variables.tf
> +  description = "Account id of customer's AWS mgmt account."
mgmt -> management

2023-08-10 18:02 UTC, ethanmil commented on variables.tf
> +  description = "Account id of customer's AWS mgmt account."
omit `customer's`

2023-08-10 18:02 UTC, ethanmil commented on variables.tf
> +  description = "Account id of customer's AWS account where the existing cloudtrail log bucket is created. This is where the new SQS queue will be created"
omit `customer's`

2023-08-10 18:03 UTC, davidmontoyago reviewed
pair-reviewed with @ethanmil

2023-08-14 14:57 UTC, davidmontoyago approved these changes
LGTM

2023-08-14 14:57 UTC, davidmontoyago commented on .circleci/config.yml
> +            EOF
💯

2023-08-14 16:05 UTC, ethanmil approved these changes
LGTM

2023-08-15 14:27 UTC, davidmontoyago approved these changes
additions 372aeda and 1a335276dd7b3ed7dfc31616629a44986dc3e22d LGTM

2023-08-15 14:34 UTC, merged